fix pyproject dependency groups and TOML parsing issue (#291)
This commit rearranges some dependencies in pyproject to be in their
appropriate dependency groups (test, types) rather than in the main
list.

Also fixed minor TOML formatting issue that caused a C++ TOML parser to
fail at `tool.mypy`:

```
error: while parsing TOML: [error] toml::insert_value: table ("tool.mypy") already exists.
 --> fromTOML
     |
 126 | [[tool.mypy.overrides]]
     | ~~~~~~~~~~~~~~~~~~~~~~~ table already exists here
 ...
 134 | [tool.mypy]
     | ~~~~~~~~~~~ table defined twice
```